version: 0.0
os: linux
files:
  - source: style.css
    destination: /var/www/html/Wordpress/wp-content/themes/twentyfourteen
hooks:
  BeforeInstall:
    - location: scripts/backup_css.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
